export const ProductionStatusEnum = {
  PENDENTE: "PENDENTE",
  PRODUCAO: "PRODUCAO",
  FINALIZADO: "FINALIZADO",
};

export const TrackingStatusEnum = {
  PENDENTE: "PENDENTE",
  POSTADO: "POSTADO",
  ENTREGUE: "ENTREGUE",
  "PROBLEMA NA ENTREGA": "PROBLEMA NA ENTREGA",
};
